# Generated by Django 2.2.16 on 2021-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211119_1229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique pair',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique pair'),
        ),
    ]
